config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :orders, only: [:index, :show, :create, :destroy]
  resources :products do
    resources :comments
  end

  get 'static_pages/about'

  get 'static_pages/contact'
  post 'static_pages/thank_you'

  get 'static_pages/index'
  root 'static_pages#landing_page'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
  has_many :comments

  validates :name, presence: true

  def highest_rating_comment
    comments.rating_desc.first
  end

  def lowest_rating_comment
    comments.rating_desc.last
  end

  def average_rating
    comments.average(:rating).to_f
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.where("name ilike ?", "%#{search_term}%")
    else
      @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    #@comments = @product.comments.paginate(page: params[:page], per_page: 2)
    #@comments = @product.comments.order("created_at DESC").paginate(page: [:page], per_page: 2)
    @comments = @product.comments.order('created_at DESC').page(params[:page]).per_page(2)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :colour, :description, :image_url, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_comments.html.erb
<div class="product-reviews">
  <%= will_paginate @comments %>
  <% @comments.each do |comment| %>
    <div class="row">
      <p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
      <% if signed_in? && current_user.admin? %>
        <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(comment.product, comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>
      <% end %>
      <p><div class="rated" data-score="<%= comment.rating %>"></div></p>
      <p><%= comment.body %></p>
    </div>
  <% end %>
  <%= will_paginate @comments %>
</div>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-horizontal col-md-6 col-md-offset-3">
    <div class="form-group">
      <%= f.text_field :name, placeholder: "Name", class: "form-control", autofocus: true %>
    </div>

    <div class="form-group">
      <%= f.text_field :colour, placeholder: "Color", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.text_area :description, placeholder: "Description", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.url_field :image_url, placeholder: "Image Url", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.number_field :price, placeholder: "Price", in: 1...50000, step: 1, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.submit "Submit", class: "btn btn-large btn-primary btn-block" %>
    </div>
  </div>

<% end %>

app/views/products/_new_comments.html.erb
<% if signed_in? %>
  <h4 class="col-md-offset-3">Add a review:</h4>
  <%= form_for([@product, @product.comments.build], html: {class: "form-horizontal col-sm-12 col-md-offset-3"}) do |f| %>
    <div class="form-group">
      <%= f.text_area :body, placeholder: "Comments", class: "form-control", autofocus: true %>
    </div>
    <div class="form-group">
      <div class="rating"></div>
    </div>
    <div class="form-group">
      <%= f.submit "Leave Comment", class: "btn btn-large btn-primary btn-block" %>
    </div>
  <% end %>
<% end %>

app/views/products/_product.html.erb
<div class="col-sm-2 col-md-4">
  <h1><%= link_to product.name, product_path(product) %></h1>
  <%= link_to image_tag(product.image_url, class: "img-responsive"), product_path(product) if product.image_url%>
  <p>Color: <%= product.colour %></p>
  <p>Description: <%= product.description %></p>
  <p>Price: $<%= product.price %></p>
</div><!-- /col -->

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<div class="container-fluid">
  <div class="row">
    <%= render @products %>
  </div>
</div>

<br>
<% if user_signed_in? %>
  <%= link_to 'New Product', new_product_path %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="showImage">
  <div class="container col-xs-12">
  <div class="product-title center-block">
    <p>
      <h2> <%= @product.name %> </h2><br/>
      <strong>Color:</strong>
      <%= @product.colour %>
    </p>
  </div>
  </div>
  <div class="product-image col-md-8">
    <%= image_tag @product.image_url, class: "img-responsive" %>
  </div>

  <div class="col-md-4 product-description text-center">
    <p>
      <h3><strong>Description:</strong>
      <%= @product.description %></h3>
    </p>
  
    <p>
      <h3><strong>Price: $
      <%= @product.price %></strong></h3>
    </p>
 
    <p>Average Rating: <div class="rated" data-score="<%= @product.average_rating %>"></div></p>
  </div>

  <div class="col-md-12">
    <p>
      <%= render 'new_comments', product: @product %>
    </p>
  </div>

  <div class="col-md-12">
    <p>
      <%= render 'comments' %>
    </p>
  </div>

  <div class="col-md-12">
    <% if user_signed_in? %>
      <%= link_to 'Edit', edit_product_path(@product) %> |
      <% if current_user.admin? %>
        <%= link_to 'Delete', product_path(@product), method: :delete, data: { confirm: 'Are Your Sure?' } %> |
      <% end %>
    <% end %>
    <%= link_to 'Back', products_path %>
  </div>
</div>