config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :orders, only: [:index, :show, :create, :destroy]
  resources :products do
    resources :comments
  end

  get 'static_pages/about'

  get 'static_pages/contact'
  post 'static_pages/thank_you'

  get 'static_pages/index'
  root 'static_pages#landing_page'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nameofapp</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel='stylesheet' type='text/css' href='http://fonts.googleapis.com/css?family=Roboto|Proza Libre'>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>
  
  <body data-spy="scroll" data-target=".navbar">
    <!-- <div class="navbar navbar-inverse navbar-fixed-top"> -->
    <nav class="navbar" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="navbar-brand">
            <%= link_to "Bike Berlin", root_path %>
          </div> <!-- end navbar-brand -->
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Products", products_path %></li>
            <li><%= link_to "About", static_pages_about_path %></li>
            <li><%= link_to "Contact", static_pages_contact_path %></li>
            <li>
            <% if user_signed_in? %>
              <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
            <% else %>
              <li><%= link_to('Login', new_user_session_path) %></li>
            <% end %>
            </li>
            <li class="navbar-form">
              <%= form_tag("/products", method: "get") do %>
                <%= text_field_tag(:q, "", placeholder: "Search") %>
                <%= submit_tag("Submit", class: "btn btn-default btn-sm") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav><!-- end nav -->

    <div class="wrapper">
      <% if notice %>
        <p id="alert" class="alert alert-info"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p id="alert" class="alert alert-info"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>

    <footer class="site-footer">
      &copy; Bike Berlin
    </footer>
  </body>
</html>